package adventOfCode2018

object DayTwo extends App {

  //PART 2

  val dayTwoTestDataPart2 = "abcde\nfghij\nklmno\npqrst\nfguij\naxcye\nwvxyz"

  def zipEm(str: String) = {
    val split = str.split("\n").toList

    

  }

  println(zipEm(dayTwoTestDataPart2))


  val dayTwoTestData: List[String] = "mgdsdwqulhrinkatfjoyzxcbvq\nmegsdwpulhrinkasfjdyzxcbvk\nmegsdwpulhmibkatfjoyzccbvq\nmegsdwtuohrinkatfjoyzecbvq\nmegsdwpulhdinkatfyoyzxcbvb\nmegszwpulhrirkatfjoyexcbvq\neegsdwpulhzinkatfjoyzxdbvq\nmegsdwpulhginkatfjoyqucbvq\nleqsdwpulhrinkatfeoyzxcbvq\nmegsdwpblhrandatfjoyzxcbvq\nmegrdwpudhrinvatfjoyzxcbvq\nmlgsdwpulhrinkatfuoyzxcbyq\nmensdwpunhrinsatfjoyzxcbvq\nmegsdwpnlhrinqatfjoyzxcbuq\nmegsdwpnlhrinkatfqoysxcbvq\nmegsdwpulhrinkjtfjoywxobvq\nmegsdwpclhbinkaffjoyzxcbvq\nmersdwpulhrinkattjoyzxcbdq\nmegsddpwohrinkatfjoyzxcbvq\nmejsdwpulhrinratfjoyzxcbvl\nmegsdwpujhrinkatfjkbzxcbvq\nmegsdwpujhrinkatfjoyircbvq\nmegsdwgulhrinkatojoyzxcbvm\nqegsdwpulhrinkatfjoyzxggvq\nmegsdwpflhrinkatfjsazxcbvq\nmegsdwpulhridkagfjoyzzcbvq\nmejsdwpulhriykatfjoyyxcbvq\nmeasdwpulhriakatfjoyzacbvq\nmebsdwpulhrinkatfjoyzxmyvq\nmegsdwpflnrinkatfjoyzxcbxq\nmegsdwpulhxinuatfjoytxcbvq\nmegsdwsflhrinkatfjoyzxcmvq\nmegsdwpuuhritkarfjoyzxcbvq\nmegsdwpulhrinkazfjoyexcjvq\nmegsdwpulhrifkatfjokzxcbvc\nmegsdwmulvrinkatfjoyzxcblq\nmeggdwpulhrfnkatfjoybxcbvq\nmegsdwptlhrindatyjoyzxcbvq\nmegsdwpulhrinkauqjoyzxibvq\nmegsdwddlhrifkatfjoyzxcbvq\nmegddwpulhrinkagfjoyzxcbva\nmessdupulhrinkatfjoyzxqbvq\nmegsdwpuahrinkatfjotzxchvq\nmegsewpulhrankathjoyzxcbvq\nmegsdwpulhrinkatfjoynqcbvv\nmegsdwpulhrifkatfjotzxcbtq\nmegsdjpulcrinkitfjoyzxcbvq\nfefsowpulhrinkatfjoyzxcbvq\nmegsdwpulapinkatfjoyzvcbvq\nmejsdwpularinkatfjonzxcbvq\nmegsxwpllrrinkatfjoyzxcbvq\nmegsdlpulxvinkatfjoyzxcbvq\nmegsdwpulhriekztfjoyzxxbvq\nmegspwpulhrinuatfjoyzxcgvq\nmegqdwpulhrinkatfjoyzujbvq\nmegsdtpuehrinkatfjoyzxtbvq\nmegsdwjulhrmnmatfjoyzxcbvq\nmegjdwpulhrinkztfjoyzpcbvq\nmegsdwpuljrinkawfjlyzxcbvq\nmewsdwpulhtinkatfjodzxcbvq\nmegsdwpulhrinkatfcoizxcmvq\nmeisdwpulhrinkatawoyzxcbvq\nmegshwpulhrinkatfjoyzxcbtz\nmegsdwpulhfinkatfjowzxcbvj\nmegodwpulhrcskatfjoyzxcbvq\nmegydxpulhrinkatfjofzxcbvq\nmegsdwpulhrinkatljoytxdbvq\nmwgsdwpulyrinkatfjoyzxvbvq\nmeesdwpulhrinkatfjcwzxcbvq\ncegsdwpwlhrinkatfioyzxcbvq\nmegsdwpulhrinkatfqhyxxcbvq\nmegsrrpulhrxnkatfjoyzxcbvq\nmegsdgpulhrinkatfjoypxcbnq\nxegsdwpulhrinkaxkjoyzxcbvq\nmngsdwpulhrenkatfjofzxcbvq\nmecsdwpulhrinkabfjoozxcbvq\npegsdkpulhrinkatfuoyzxcbvq\nmegpdwpughrinkatfjoyzxzbvq\nmxgrdwpulhrinyatfjoyzxcbvq\nmegsdwpulhpigkatfjoyzxcbfq\nmhgsdwpulhrinkagfjoxzxcbvq\nmegsdwpblhtinkatfjqyzxcbvq\nmegsawvulhrinkatfjoyzxcfvq\nmetsuwpulhrinkatfjowzxcbvq\nmexsdwpulhrinkatsjoyzxvbvq\nmegtdwpulhrinkatfjoizxcpvq\nmegidwpjlhrinkatfdoyzxcbvq\nmegsdwpuljrivkatfjoyqxcbvq\nmespdppulhrinkatfjoyzxcbvq\nmegsdcpulhminkatftoyzxcbvq\nmegsdwpulhriskatfjayzlcbvq\nmejsdwpulhrinkatfvoyzxibvq\nmegfdwputhriykatfjoyzxcbvq\nmegsdwparhrinkbtfjoyzxcbvq\nmtgsdwpulhmingatfjoyzxcbvq\nmegsdwjulhrinkatfjtyzxtbvq\nmegsvwpulhrinkatfjoyzecbvf\nmegsdwpulprinkatyqoyzxcbvq\nzegsdwpulhwinkatfjoyzxcfvq\nmegsdwiulhrinkatfjoyzxcjcq\naegsdwpulirinkatfjoyvxcbvq\nmepsdwculbrinkatfjoyzxcbvq\nmsgsdcpulhrinkctfjoyzxcbvq\nmegsdwpulhrinkatfjoozxfevq\nmegscwpulhrinkatmjoyzxcbsq\nmegsdwpulhrinkltfjoyzxtmvq\nmegsddpulhrixkatfjyyzxcbvq\nmegsdwpulhrinkctfjoqzhcbvq\nmegsbapblhrinkatfjoyzxcbvq\nmegsdwpulhrinkatfjoyyxgpvq\nmwpsdwpulhrinkutfjoyzxcbvq\nmegsdwpulhrinvnlfjoyzxcbvq\nmegsdwsulorinkakfjoyzxcbvq\nmbgsdwpulhrinkktfjoyzxcbvg\nmegddwpulhrindatfjoyzxcbvr\nmemsdwpulhrinkatqjoyzxcbvo\nmegsdwpulbrinkarfjoyzxcbxq\nmegsdwpulhrilkatfjoynxcgvq\nmxgsdzpulhrinkatfjoydxcbvq\nmegsawpulhrinkotfjoyzacbvq\nmeasdwpulhrinkctvjoyzxcbvq\nmedsdwpulhtinkaqfjoyzxcbvq\nmegsdwsulhrknkatfjoylxcbvq\nmegadwpulhrinkatfjkyzxcbvh\nmygsdwpulhrinkatfboyzxcavq\nmegsdwpulhrinkaufjxyzccbvq\nmtgsdwpulhrunkatfkoyzxcbvq\nmegsdwpulhrinkamfwryzxcbvq\nmeesdwpulhrgnkatnjoyzxcbvq\nmegddwpolhrinkatfjoyixcbvq\nmegsdwpulhrinsatfjoyzicwvq\nmmgsdwpulhrinkltfjoyzxcgvq\nmeisdwpulhhinkatfjoyzxubvq\nmegpdwpulhrinkatfroyzxcbkq\nmegszwpuhhrinkatfjoyzxcbzq\nmersdwpulhrikcatfjoyzxcbvq\nmjgsdwpulhrinratfjoyzxcbvl\nmegsdwnulkxinkatfjoyzxcbvq\nmegsdwpulhrinkatlaoyzxpbvq\nmegsdwpulhribkitfjjyzxcbvq\nmegsdwpzlhrinkalfjoyzkcbvq\nmegsdwpulhrinkutfjoyzxcdnq\nmfgpdwputhrinkatfjoyzxcbvq\noegshwpclhrinkatfjoyzxcbvq\nmegvdwxulhrinkatfjowzxcbvq\nmrgydwpulhrinkatfjoyzxcbvl\nmegsdwpuqhrinkaxfjoyzxcbfq\nmegsdwpughrinixtfjoyzxcbvq\nmegsdwpslxrinkatfjoyzxcbvl\nmegsdwpukhrinkatfjovzxnbvq\nmegsdwpulnrinkrtojoyzxcbvq\nmegsdwpuvhrinkatfjjyzxclvq\nvegrdwpulhrinzatfjoyzxcbvq\nmelsdwwulvrinkatfjoyzxcbvq\nmegsdwpulhrizkbtfjoyzjcbvq\nmegsdwpulhrinlatfjoyzkcbvr\nmegsdweulhrinkaofqoyzxcbvq\nmegsdcpulhrifkatfdoyzxcbvq\nnegsdwpulhainkztfjoyzxcbvq\nmegsdwpklhrinkttfjoyzxvbvq\nmegsdwpothrdnkatfjoyzxcbvq\nmegsdwpulvrinkatfaoyzxcbvr\nmewsdwpulhrinkatfooyzxtbvq\nmegtdwpulhrinkatfxoyzxcbvy\nzegsdwpulhrinkamljoyzxcbvq\nmkgodwpulhrcnkatfjoyzxcbvq\nmegsdepularinkatfjoyzxybvq\nsegsdwpulhrinkatfmoyzycbvq\nmbgsdwpulhrsnkztfjoyzxcbvq\nmegsdwpmlhrinkatfjxyzhcbvq\nmegsdwpulhrinkatfboyqxmbvq\nmegsdwpulhrinkadtpoyzxcbvq\nmegsdmpulhrjnkatfjoyzxwbvq\nmegsdwpulhrivkatfroywxcbvq\nmegsdwdulhrinkatpjwyzxcbvq\nmegsdwpylhrdrkatfjoyzxcbvq\nmegsdwpulhrvnkptfjoyzlcbvq\nmegsdwpuihridkatfjuyzxcbvq\nmegsdwpulhbiikatfjxyzxcbvq\nmeggdwpulurinkatfjoyaxcbvq\nmehsnwpulcrinkatfjoyzxcbvq\nmegsdwpulhrinkatfjoczdclvq\nmegsdwjulhrinkatfhkyzxcbvq\nmegsdwpulhrinoatfjoyzxcwvy\nmegpdwpelhrfnkatfjoyzxcbvq\nmegsjwpulhrwnkatfjdyzxcbvq\nmegsdwpulhrbniatfjoyzxcbpq\nmegsdwpulhrwnkatfjoydxcpvq\nmegsdwrulhrinkatfjvyixcbvq\nyegvdwpulhtinkatfjoyzxcbvq\nmeosdwpulhrinkatfjhyzxsbvq\nmjgsdwpulhrinkatfjoyyxcjvq\nmegsdwpulhrinkatfnoyzlmbvq\nmehsdfkulhrinkatfjoyzxcbvq\nmegsdwpuahrinkatfyoyzxcwvq\nmegsdwpulhyinkatfjobzkcbvq\nmegsdwpjlhrinkatfnoyzscbvq\nmegsdwiulhrinqatfjoyzxcavq\nmegsdwpulurinkatfjoykxcbmq\nmegsdwpmlhvinkatfjotzxcbvq\nmegswwpulhrinfatfjoytxcbvq\nmxgsdwpulhrrnkatfjoyhxcbvq\nmegubwpulhrinkaafjoyzxcbvq\nmegsdwpulhrdnsztfjoyzxcbvq\nmegsdwpulhronkgtfjhyzxcbvq\nmegsdwzulhfinratfjoyzxcbvq\nmegsdwpulhrinkrtfjqyixcbvq\nmegspwpulhrinkatfjoywxcavq\nmegmfjpulhrinkatfjoyzxcbvq\nlelsdwpulhrinsatfjoyzxcbvq\nmegsdwnultrinkatfjoyzxybvq\nmegsdwpulhdnnkatfjpyzxcbvq\nmegsdwpulhzinkatfjoyzhcpvq\nmegoddpulhrilkatfjoyzxcbvq\nmegsdvpulhrwnkatfjoyzxcbdq\nmegsdwpulhmikkatfjoyzxcbvr\nmeesdwpulhrinkaofjoazxcbvq\nmegndwhulhrinfatfjoyzxcbvq\nmegsdwpulhjihkatfjoyzxcbvb\njegsdwpulhrinkattjoszxcbvq\nmegsdwpulhrenkatfjodzxcbvp\nmefsdwpulhrinkatfjoyzxcczq\nmegsdwpulhrknkatfjovzxcbvb\nmegytwpulhrinkatfjoyzxcbvo\ncsgsdwpulhrinkatdjoyzxcbvq\nmegsbwpulhrinkazfjtyzxcbvq\nmrgsdwpulhjinkatfjoyzxcbvm\nmegsywzulhrinkatfjofzxcbvq\nmegxdwpulhrndkatfjoyzxcbvq\nmcgsdwpuphrixkatfjoyzxcbvq\nmegsdlpulxvinkatfvoyzxcbvq\nmegsdwpulhrinfatfjoyzicbvo\nmegwgwpulhrinpatfjoyzxcbvq\nmggsdwpulhrinkatfjtrzxcbvq\nmsgsdwpulirinkatfjoyzxcbaq\nmegsdwpulhrineatfeoyzxcbvl\nmegsdnpulhrinkatojoyzxcbvb\nmfgsdwpulhdinkatmjoyzxcbvq\nmegsdwpulhrinkawfjuyzxcbvg\nmegsdwpulhrincatfjoyzxcxvu\nmevsdwzplhrinkatfjoyzxcbvq\nmegskweulhfinkatfjoyzxcbvq\nmebsdvpulhrinkatfjoyzxcbkq\nmegddwiulhrinkatfioyzxcbvq\nmygsdwpulhqinkatfooyzxcbvq\nmegsdweulhrfnkatfjoybxcbvq\nmrgsdhpulmrinkatfjoyzxcbvq\nmegsdwkukhrinkatftoyzxcbvq\nmegsqwpulhrinfatfjoyzxebvq\nmegsdwpulhriskanfjoyzxctvq"
    .split("\n").toList

  val x: List[List[String]] = dayTwoTestData.map(_.groupBy(identity).values.toList)

  def findLetters(input: List[List[String]]): Int = {

    val turnToInt = input.map(_.map(_.length))

    val twos = turnToInt.foldLeft(0) { (acc, curr) =>
      if (curr.contains(2)) acc + 1
      else acc
    }

    val threes = turnToInt.foldLeft(0) { (acc, curr) =>
      if (curr.contains(3)) acc + 1
      else acc
    }

    twos * threes

  }

  //println(findLetters(x))

}
